language: java
jdk:
  - openjdk14
sudo: false
env:
  global:

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - alienoman@rambler.ru
    on_success: never
    on_failure: always
